version: '3.6'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8181:8181
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example     
      VCAP_APP_PORT: 8181 
  order-service:
    build: order-service/.
  # inventory-service:
  #   build: inventory-service/.
  payments-service:
    build: payments-service/.
  shipping-service:
    build: shipping-service/.
